### Build app
FROM golang:1.19 AS build

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY service/ /app/service/
WORKDIR /app/service/webapp
RUN go build -o /webapp

### Copy app to runtime container
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /webapp /webapp

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/webapp"]