##################################################################################################
# webapp
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    service: webapp
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocservice-webapp
  labels:
    account: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      serviceAccountName: pocservice-webapp
      containers:
      - name: webapp
        image: ryogokacr.azurecr.io/webapp:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TARGET_HOST
          value: "compute.ryogokpoc.svc.cluster.local"
        - name: TARGET_PORT
          value: "8081"
        - name: AZURE_STORAGE_CONNECTION_STRING
          value: "<connection_string>"
        ports:
        - containerPort: 8080
---
##################################################################################################
# compute
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: compute
  labels:
    app: compute
    service: compute
spec:
  selector:
    app: compute
  ports:
  - name: http
    port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pocservice-compute
  labels:
    account: compute
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-p1
  labels:
    app: compute
    partition: p1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute
      partition: p1
  template:
    metadata:
      labels:
        app: compute
        partition: p1
    spec:
      serviceAccountName: pocservice-compute
      containers:
      - name: compute
        image: ryogokacr.azurecr.io/compute:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compute-p2
  labels:
    app: compute
    partition: p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute
      partition: p2
  template:
    metadata:
      labels:
        app: compute
        partition: p2
    spec:
      serviceAccountName: pocservice-compute
      containers:
      - name: compute
        image: ryogokacr.azurecr.io/compute:v1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8081